title: 'Ignited Ember'
default_lang: en
author:
  name: 'Jordan Medrano'
  email: jordanmedrano@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Ignited Ember is a Gold/Platinum ranked Overwatch team'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
