enabled: true
production-mode: false
grid-size: grid-xl
header-fixed: true
header-animated: true
header-dark: false
header-transparent: true
sticky-footer: false
blog-page: '/blog'
spectre:
  exp: false
  icons: false
custom_logo:
    - name: 'logo.png'